name: travel_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter_calendar_carousel: ^2.4.2
  intl: ^0.18.1
  flutter:
    sdk: flutter
  provider: ^6.1.1

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  google_sign_in: ^6.1.6
  firebase_storage: ^11.5.3
  google_maps_flutter: ^2.5.0
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4

dev_dependencies:
  flutter_gen: ^5.3.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/

  uses-material-design: true
